name: Test Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Force failure
        run: |
          echo "Start"
          invalid_command_here
